In [207]:
# Leer el archivo de ataques de tiburones
# Ubicar que columna necesita limpieza
# Cambiar el nombre a las columnas
# Eliminar filas sin informacion
# Modificar contenido de columnas
# Cambiar el formato de la hora
# Anadir 0 en el vacio de informacion
# Crear funcion en species para remover nan

import pandas as pd
import numpy as np
import hashlib
import re
from urllib.parse import urlparse

In [208]:
tabla = pd.read_csv('attacks.csv', encoding = 'latin1')
tabla.head()

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,...,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0,NaN,NaN
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,...,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0,NaN,NaN
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,...,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0,NaN,NaN
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,...,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300.0,NaN,NaN
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,...,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299.0,NaN,NaN

In [209]:
# dictionary like

tabla['Date']

0        25-Jun-2018
1        18-Jun-2018
2        09-Jun-2018
3        08-Jun-2018
4        04-Jun-2018
            ...
25718            NaN
25719            NaN
25720            NaN
25721            NaN
25722            NaN
Name: Date, Length: 25723, dtype: object

In [210]:
tabla[['Area', 'Location']]

                  Area                        Location
0           California     Oceanside, San Diego County
1              Georgia  St. Simon Island, Glynn County
2               Hawaii                    Habush, Oahu
3      New South Wales              Arrawarra Headland
4               Colima                        La Ticla
...                ...                             ...
25718              NaN                             NaN
25719              NaN                             NaN
25720              NaN                             NaN
25721              NaN                             NaN
25722              NaN                             NaN

[25723 rows x 2 columns]

In [211]:
# Numpy like

tabla.iloc[10:15]

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
10,2018.05.24,24-May-2018,2018.0,Provoked,AUSTRALIA,Queensland,Cairns Aquarium,Feeding sharks,male,M,...,Grey reef shark,"ABC.net.au ,05/24/2018",2018.05.24-CairnsAquarium.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.24,2018.05.24,6293.0,NaN,NaN
11,2018.05.21,21-May-2018,2018.0,Unprovoked,USA,South Carolina,"Isle of Palms, Charleston County",Boogie boarding,Trey de Boer,M,...,NaN,"C. Creswell, GSAF",2018.05.21-deBoer.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.21,2018.05.21,6292.0,NaN,NaN
12,2018.05.13.b,13-May-2018,2018.0,Unprovoked,USA,South Carolina,"Hilton Head Island, Beaufort County",Swimming,Jei Turrell,M,...,NaN,"C. Creswell, GSAF & K. McMurray TrackingSharks...",2018.05.13.b-Turrell.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.13.b,2018.05.13.b,6291.0,NaN,NaN
13,2018.05.13.a,13-May-2018,2018.0,Invalid,ENGLAND,Cornwall,Off Land's End,Fishing,Max Berryman,M,...,Invalid incident,"K. McMurray, TrackingSharks.com",2018.05.13.a-Berryman.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.13.a,2018.05.13.a,6290.0,NaN,NaN
14,2018.05.00,May 2018,2018.0,Provoked,AUSTRALIA,Westerm Australia,Dugong Bay,Feeding sharks,Melisa Brunning,F,...,"Tawny nurse shark, 2m","Perth Now, 6/30/2018",2018.05.00-Brunning.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.00,2018.05.00,6289.0,NaN,NaN

In [212]:
tabla.iloc[13]['Date']

'13-May-2018'

In [213]:
tabla.iloc[:5,  0]

0    2018.06.25
1    2018.06.18
2    2018.06.09
3    2018.06.08
4    2018.06.04
Name: Case Number, dtype: object

In [214]:
tabla.loc[:, 'Type': 'Name' ]

,Type,Country,Area,Location,Activity,Name
0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe
1,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely
2,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges
3,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male
4,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos
...,...,...,...,...,...,...
25718,NaN,NaN,NaN,NaN,NaN,NaN
25719,NaN,NaN,NaN,NaN,NaN,NaN
25720,NaN,NaN,NaN,NaN,NaN,NaN
25721,NaN,NaN,NaN,NaN,NaN,NaN
25722,NaN,NaN,NaN,NaN,NaN,NaN

# Data wrangling

In [215]:
# 1. Anadir newspapar

In [216]:
# tabla['Columna'] = 'Tabla'

In [217]:
# Obtener el host

# tabla['host'] = tabla['href'].apply(lambda href: urlparse(href).netloc)

In [218]:
tabla['pdf'].value_counts()

1931.09.21.a-b-Holaday-Barrows.pdf     2
1921.11.27.a-b-Jack.pdf                2
1906.09.27.R.a&b-Munich-Swede.pdf      2
1916.07.12.a-b-Stillwell-Fisher.pdf    2
1907.10.16.R-HongKong.pdf              2
                                      ..
1902.06.00-Giorgos.pdf                 1
1975.04.05-Thompson.pdf                1
2000.10.20-Licamele.pdf                1
2016.04.13-Senkowicz.pdf               1
1963.12.21-Cook.pdf                    1
Name: pdf, Length: 6291, dtype: int64

In [219]:
# 3. REllenar datos faltantes

#missing_titles_mask = tabla['Type'].isna()

#(tabla[missing_titles_mask]['href']
#   .str.extract(r'(?P<missing_type>[^/]+)$')
#   .applymap(lambda title: title.split('-'))
#   .applymap(lambda title_word_list: ' '.join(title_word_list))
#    )
#missing_titles_mask

In [220]:
#uids = (tabla
#           .apply(lambda row: hashlib.md5(bytes(row['href'].encode())), axis = 1)
#           .apply(lambda hash_object: hash_objetct.hexdigest())
#       )
#tabla['href'] = uids
#tabla.set_index['href', inplace = True]

#tabla

In [221]:
tabla.shape

(25723, 24)

In [222]:
tabla.columns

Index(['Case Number', 'Date', 'Year', 'Type', 'Country', 'Area', 'Location',
       'Activity', 'Name', 'Sex ', 'Age', 'Injury', 'Fatal (Y/N)', 'Time',
       'Species ', 'Investigator or Source', 'pdf', 'href formula', 'href',
       'Case Number.1', 'Case Number.2', 'original order', 'Unnamed: 22',
       'Unnamed: 23'],
      dtype='object')

In [223]:
tabla_clean=tabla.drop(columns=['Area'])
print (tabla.columns.shape)
print (tabla_clean.columns.shape)
print (type(tabla_clean.columns.shape))

(24,)
(23,)
<class 'tuple'>

In [224]:
null_cols=tabla_clean.isnull().sum()
null_cols[null_cols>0]

Case Number               17021
Date                      19421
Year                      19423
Type                      19425
Country                   19471
Location                  19961
Activity                  19965
Name                      19631
Sex                       19986
Age                       22252
Injury                    19449
Fatal (Y/N)               19960
Time                      22775
Species                   22259
Investigator or Source    19438
pdf                       19421
href formula              19422
href                      19421
Case Number.1             19421
Case Number.2             19421
original order            19414
Unnamed: 22               25722
Unnamed: 23               25721
dtype: int64

In [225]:
tabla.sum()

Year              12141816.0
original order    19911202.0
dtype: float64

In [226]:
type(tabla)

pandas.core.frame.DataFrame

In [227]:
tabla.dtypes

Case Number                object
Date                       object
Year                      float64
Type                       object
Country                    object
Area                       object
Location                   object
Activity                   object
Name                       object
Sex                        object
Age                        object
Injury                     object
Fatal (Y/N)                object
Time                       object
Species                    object
Investigator or Source     object
pdf                        object
href formula               object
href                       object
Case Number.1              object
Case Number.2              object
original order            float64
Unnamed: 22                object
Unnamed: 23                object
dtype: object

In [228]:
tabla.Area.value_counts(sort='ascending')

Florida            1037
New South Wales     486
Queensland          311
Hawaii              298
California          290
                   ...
Anjouan               1
Moala Island          1
Jeju Province         1
Taranto               1
Conakry Region        1
Name: Area, Length: 825, dtype: int64

In [229]:
regex = r'^(\d{4})'

In [230]:
tabla.columns 
print(tabla['Name'])

0            Julie Wolfe
1        Adyson McNeely
2            John Denges
3                   male
4         Gustavo Ramos
              ...
25718                NaN
25719                NaN
25720                NaN
25721                NaN
25722                NaN
Name: Name, Length: 25723, dtype: object

In [231]:
tabla2 = tabla.rename(columns={'Area':'State', 
                              'Case Number':'Date Numerica', 'pdf':'Formato pdf', 'href formula':'Localizador Uniforma de Recursos','href':'URL'})

tabla2.columns

Index(['Date Numerica', 'Date', 'Year', 'Type', 'Country', 'State', 'Location',
       'Activity', 'Name', 'Sex ', 'Age', 'Injury', 'Fatal (Y/N)', 'Time',
       'Species ', 'Investigator or Source', 'Formato pdf',
       'Localizador Uniforma de Recursos', 'URL', 'Case Number.1',
       'Case Number.2', 'original order', 'Unnamed: 22', 'Unnamed: 23'],
      dtype='object')

In [232]:
tabla2.head()

,Date Numerica,Date,Year,Type,Country,State,Location,Activity,Name,Sex,...,Species,Investigator or Source,Formato pdf,Localizador Uniforma de Recursos,URL,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,...,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0,NaN,NaN
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,...,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0,NaN,NaN
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,...,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0,NaN,NaN
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,...,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300.0,NaN,NaN
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,...,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299.0,NaN,NaN

In [233]:
# Eliminar la información innecesaria así como dichas columnas
del tabla2['Unnamed: 22']
del tabla2['Unnamed: 23']
del tabla2['URL']

In [234]:
tabla2.head()

,Date Numerica,Date,Year,Type,Country,State,Location,Activity,Name,Sex,...,Injury,Fatal (Y/N),Time,Species,Investigator or Source,Formato pdf,Localizador Uniforma de Recursos,Case Number.1,Case Number.2,original order
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,...,"No injury to occupant, outrigger canoe and pad...",N,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,...,Minor injury to left thigh,N,14h00 -15h00,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,...,Injury to left lower leg from surfboard skeg,N,07h45,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,...,Minor injury to lower leg,N,NaN,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300.0
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,...,Lacerations to leg & hand shark PROVOKED INCIDENT,N,NaN,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299.0

In [235]:
# Llenado donde no existe información
tabla2 = tabla2.fillna('')
tabla2

,Date Numerica,Date,Year,Type,Country,State,Location,Activity,Name,Sex,...,Injury,Fatal (Y/N),Time,Species,Investigator or Source,Formato pdf,Localizador Uniforma de Recursos,Case Number.1,Case Number.2,original order
0,2018.06.25,25-Jun-2018,2018,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,...,"No injury to occupant, outrigger canoe and pad...",N,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303
1,2018.06.18,18-Jun-2018,2018,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,...,Minor injury to left thigh,N,14h00 -15h00,,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302
2,2018.06.09,09-Jun-2018,2018,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,...,Injury to left lower leg from surfboard skeg,N,07h45,,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301
3,2018.06.08,08-Jun-2018,2018,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,...,Minor injury to lower leg,N,,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300
4,2018.06.04,04-Jun-2018,2018,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,...,Lacerations to leg & hand shark PROVOKED INCIDENT,N,,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25718,,,,,,,,,,,...,,,,,,,,,,
25719,,,,,,,,,,,...,,,,,,,,,,
25720,,,,,,,,,,,...,,,,,,,,,,
25721,,,,,,,,,,,...,,,,,,,,,,
25722,xx,,,,,,,,,,...,,,,,,,,,,

In [236]:
tabla2.columns

Index(['Date Numerica', 'Date', 'Year', 'Type', 'Country', 'State', 'Location',
       'Activity', 'Name', 'Sex ', 'Age', 'Injury', 'Fatal (Y/N)', 'Time',
       'Species ', 'Investigator or Source', 'Formato pdf',
       'Localizador Uniforma de Recursos', 'Case Number.1', 'Case Number.2',
       'original order'],
      dtype='object')

In [237]:
# Localizar variables en la limpia de tabla2
stripped_body = (tabla2.apply(lambda row: row['Location'], axis=1))
stripped_body

tabla2.loc[tabla2['Name']== 'male']

,Date Numerica,Date,Year,Type,Country,State,Location,Activity,Name,Sex,...,Injury,Fatal (Y/N),Time,Species,Investigator or Source,Formato pdf,Localizador Uniforma de Recursos,Case Number.1,Case Number.2,original order
3,2018.06.08,08-Jun-2018,2018,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,...,Minor injury to lower leg,N,,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300
7,2018.05.27,27-May-2018,2018,Unprovoked,USA,Florida,"Lighhouse Point Park, Ponce Inlet, Volusia County",Fishing,male,M,...,Minor injury to foot. PROVOKED INCIDENT,N,,"Lemon shark, 3'","K. McMurray, TrackingSharks.com",2018.05.27-Ponce.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.27,2018.05.27,6296
9,2018.05.26.a,26-May-2018,2018,Unprovoked,USA,Florida,"Daytona Beach, Volusia County",Standing,male,M,...,Minor injury to foot,N,14h00,,"K. McMurray, Tracking Sharks.com",2018.05.26.a-DaytonaBeach.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.26.a,2018.05.26.a,6294
10,2018.05.24,24-May-2018,2018,Provoked,AUSTRALIA,Queensland,Cairns Aquarium,Feeding sharks,male,M,...,Minor bite to hand by captive shark. PROVOKED ...,N,Morning,Grey reef shark,"ABC.net.au ,05/24/2018",2018.05.24-CairnsAquarium.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.24,2018.05.24,6293
15,2018.05.12,12-May-2018,2018,Unprovoked,SOUTH AFRICA,Eastern Cape Province,"Nahoon Beach, East London",Surfing,male,M,...,"Minor injury, marks on board",N,11h00,,"B.Jacob, Dispatch Live, 5/12/2018",2018.05.12-EastLondon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.12,2018.05.12,6288
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6273,ND.0030,Before 1905,0,Unprovoked,BURMA,,,Bathing,male,M,...,Fatal x 2,Y,,,"Massillon Independent, 3/1905",ND-0030-Burma.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0030,ND.0030,30
6285,ND.0017,Before 1921,0,Unprovoked,SOUTH AFRICA,KwaZulu-Natal,Durban,Crew swimming alongside their anchored ship,male,M,...,FATAL,Y,,,"Captain A. Anderson, Natal Mercury, 12/31/192...",ND-0017-alongside-ship.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0017,ND.0017,18
6286,ND.0016,Before 1921,0,Unprovoked,SOUTH AFRICA,KwaZulu-Natal,Durban,4 men were bathing,male,M,...,FATAL,Y,,,"Captain A. Anderson, Natal Mercury, 12/31/192...",ND-0016- Durban-PostOffice.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0016,ND.0016,17
6297,ND.0005,Before 1903,0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,M,...,FATAL,Y,,,"H. Taunton; N. Bartlett, p. 234",ND-0005-RoebuckBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0005,ND.0005,6
6301,ND.0001,1845-1853,0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,...,"FATAL. ""Shark bit him in half, carrying away t...",Y,,,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0001,ND.0001,2

In [238]:
tabla2.loc[tabla2['Name'].str.contains('male', flags = re.I, regex = True)]

,Date Numerica,Date,Year,Type,Country,State,Location,Activity,Name,Sex,...,Injury,Fatal (Y/N),Time,Species,Investigator or Source,Formato pdf,Localizador Uniforma de Recursos,Case Number.1,Case Number.2,original order
3,2018.06.08,08-Jun-2018,2018,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,...,Minor injury to lower leg,N,,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300
7,2018.05.27,27-May-2018,2018,Unprovoked,USA,Florida,"Lighhouse Point Park, Ponce Inlet, Volusia County",Fishing,male,M,...,Minor injury to foot. PROVOKED INCIDENT,N,,"Lemon shark, 3'","K. McMurray, TrackingSharks.com",2018.05.27-Ponce.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.27,2018.05.27,6296
9,2018.05.26.a,26-May-2018,2018,Unprovoked,USA,Florida,"Daytona Beach, Volusia County",Standing,male,M,...,Minor injury to foot,N,14h00,,"K. McMurray, Tracking Sharks.com",2018.05.26.a-DaytonaBeach.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.26.a,2018.05.26.a,6294
10,2018.05.24,24-May-2018,2018,Provoked,AUSTRALIA,Queensland,Cairns Aquarium,Feeding sharks,male,M,...,Minor bite to hand by captive shark. PROVOKED ...,N,Morning,Grey reef shark,"ABC.net.au ,05/24/2018",2018.05.24-CairnsAquarium.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.24,2018.05.24,6293
15,2018.05.12,12-May-2018,2018,Unprovoked,SOUTH AFRICA,Eastern Cape Province,"Nahoon Beach, East London",Surfing,male,M,...,"Minor injury, marks on board",N,11h00,,"B.Jacob, Dispatch Live, 5/12/2018",2018.05.12-EastLondon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.12,2018.05.12,6288
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6285,ND.0017,Before 1921,0,Unprovoked,SOUTH AFRICA,KwaZulu-Natal,Durban,Crew swimming alongside their anchored ship,male,M,...,FATAL,Y,,,"Captain A. Anderson, Natal Mercury, 12/31/192...",ND-0017-alongside-ship.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0017,ND.0017,18
6286,ND.0016,Before 1921,0,Unprovoked,SOUTH AFRICA,KwaZulu-Natal,Durban,4 men were bathing,male,M,...,FATAL,Y,,,"Captain A. Anderson, Natal Mercury, 12/31/192...",ND-0016- Durban-PostOffice.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0016,ND.0016,17
6288,ND.0014,Before 17-Jul-1916,0,Unprovoked,USA,North Carolina,Somewhere between Hatteras and Beaufort,Swimming,"""youthful male""",M,...,"""Lost leg""",N,,,"C. Creswell, GSAF; Wilmington Star, 7/17/1916",ND-0014-pre1916-NorthCarolina.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0014,ND.0014,15
6297,ND.0005,Before 1903,0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,M,...,FATAL,Y,,,"H. Taunton; N. Bartlett, p. 234",ND-0005-RoebuckBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0005,ND.0005,6
6301,ND.0001,1845-1853,0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,...,"FATAL. ""Shark bit him in half, carrying away t...",Y,,,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0001,ND.0001,2

In [239]:
def get_NON(item):
    if ' NaN' in item:
        return item[:item.find(' NaN')]
    elif ',' in item:
        return item[:item.find(',')]
    else:
        return item

In [240]:
tabla2['Date'].value_counts()

               19421
1957              11
1942               9
1956               8
1958               7
               ...
06-Oct-1988        1
05-Jul-1883        1
1839/1840          1
10-Apr-2013        1
18-Nov-1964        1
Name: Date, Length: 5434, dtype: int64

In [241]:
# Cambiar la palabra male por no exist de la columna nombre
tabla2.loc[tabla['Name']== 'male', ['Name']] = 'No exist'
tabla2

,Date Numerica,Date,Year,Type,Country,State,Location,Activity,Name,Sex,...,Injury,Fatal (Y/N),Time,Species,Investigator or Source,Formato pdf,Localizador Uniforma de Recursos,Case Number.1,Case Number.2,original order
0,2018.06.25,25-Jun-2018,2018,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,...,"No injury to occupant, outrigger canoe and pad...",N,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303
1,2018.06.18,18-Jun-2018,2018,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,...,Minor injury to left thigh,N,14h00 -15h00,,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302
2,2018.06.09,09-Jun-2018,2018,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,...,Injury to left lower leg from surfboard skeg,N,07h45,,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301
3,2018.06.08,08-Jun-2018,2018,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,No exist,M,...,Minor injury to lower leg,N,,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300
4,2018.06.04,04-Jun-2018,2018,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,...,Lacerations to leg & hand shark PROVOKED INCIDENT,N,,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25718,,,,,,,,,,,...,,,,,,,,,,
25719,,,,,,,,,,,...,,,,,,,,,,
25720,,,,,,,,,,,...,,,,,,,,,,
25721,,,,,,,,,,,...,,,,,,,,,,
25722,xx,,,,,,,,,,...,,,,,,,,,,

In [242]:
# Cambio de int a str
tabla['Year'].astype('str')

0        2018.0
1        2018.0
2        2018.0
3        2018.0
4        2018.0
          ...
25718       nan
25719       nan
25720       nan
25721       nan
25722       nan
Name: Year, Length: 25723, dtype: object

In [243]:
# Asignar un guion a lo que no tiene nada de informacion
tabla2.loc[tabla2['Year']== '',['Year', 'Date Numerica']] = 0
tabla2

,Date Numerica,Date,Year,Type,Country,State,Location,Activity,Name,Sex,...,Injury,Fatal (Y/N),Time,Species,Investigator or Source,Formato pdf,Localizador Uniforma de Recursos,Case Number.1,Case Number.2,original order
0,2018.06.25,25-Jun-2018,2018,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,...,"No injury to occupant, outrigger canoe and pad...",N,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303
1,2018.06.18,18-Jun-2018,2018,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,...,Minor injury to left thigh,N,14h00 -15h00,,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302
2,2018.06.09,09-Jun-2018,2018,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,...,Injury to left lower leg from surfboard skeg,N,07h45,,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301
3,2018.06.08,08-Jun-2018,2018,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,No exist,M,...,Minor injury to lower leg,N,,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300
4,2018.06.04,04-Jun-2018,2018,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,...,Lacerations to leg & hand shark PROVOKED INCIDENT,N,,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25718,0,,0,,,,,,,,...,,,,,,,,,,
25719,0,,0,,,,,,,,...,,,,,,,,,,
25720,0,,0,,,,,,,,...,,,,,,,,,,
25721,0,,0,,,,,,,,...,,,,,,,,,,
25722,0,,0,,,,,,,,...,,,,,,,,,,

In [244]:
# Convertir a int y asignar valor a los '0'
tabla2['Year'].astype('int')
tabla2.loc[tabla2['Year'] <1000,['Year']] = 'No year info'
tabla2

,Date Numerica,Date,Year,Type,Country,State,Location,Activity,Name,Sex,...,Injury,Fatal (Y/N),Time,Species,Investigator or Source,Formato pdf,Localizador Uniforma de Recursos,Case Number.1,Case Number.2,original order
0,2018.06.25,25-Jun-2018,2018,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,...,"No injury to occupant, outrigger canoe and pad...",N,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303
1,2018.06.18,18-Jun-2018,2018,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,...,Minor injury to left thigh,N,14h00 -15h00,,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302
2,2018.06.09,09-Jun-2018,2018,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,...,Injury to left lower leg from surfboard skeg,N,07h45,,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301
3,2018.06.08,08-Jun-2018,2018,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,No exist,M,...,Minor injury to lower leg,N,,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300
4,2018.06.04,04-Jun-2018,2018,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,...,Lacerations to leg & hand shark PROVOKED INCIDENT,N,,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25718,0,,No year info,,,,,,,,...,,,,,,,,,,
25719,0,,No year info,,,,,,,,...,,,,,,,,,,
25720,0,,No year info,,,,,,,,...,,,,,,,,,,
25721,0,,No year info,,,,,,,,...,,,,,,,,,,
25722,0,,No year info,,,,,,,,...,,,,,,,,,,

In [245]:
tabla2.loc[tabla2['Age'].str.contains('[A-Z]', flags=re.I, regex = True)]
tabla2

,Date Numerica,Date,Year,Type,Country,State,Location,Activity,Name,Sex,...,Injury,Fatal (Y/N),Time,Species,Investigator or Source,Formato pdf,Localizador Uniforma de Recursos,Case Number.1,Case Number.2,original order
0,2018.06.25,25-Jun-2018,2018,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,...,"No injury to occupant, outrigger canoe and pad...",N,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303
1,2018.06.18,18-Jun-2018,2018,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,...,Minor injury to left thigh,N,14h00 -15h00,,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302
2,2018.06.09,09-Jun-2018,2018,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,...,Injury to left lower leg from surfboard skeg,N,07h45,,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301
3,2018.06.08,08-Jun-2018,2018,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,No exist,M,...,Minor injury to lower leg,N,,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300
4,2018.06.04,04-Jun-2018,2018,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,...,Lacerations to leg & hand shark PROVOKED INCIDENT,N,,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25718,0,,No year info,,,,,,,,...,,,,,,,,,,
25719,0,,No year info,,,,,,,,...,,,,,,,,,,
25720,0,,No year info,,,,,,,,...,,,,,,,,,,
25721,0,,No year info,,,,,,,,...,,,,,,,,,,
25722,0,,No year info,,,,,,,,...,,,,,,,,,,

In [246]:
# tabla2['Age'].head(40)

In [254]:
#MODIFICANDO COLUMNA Sex

tabla2['Sex']= tabla2['Sex'].str.replace('F', 'Female')

KeyError: 'Sex'

In [251]:
#Ajuste COLUMNA TIME
tabla2.loc[tabla2.Time == 'Afternoon', 'Time'] = '12:00'
tabla2.loc[tabla2.Time == '14h00-15h00', 'Time'] = '14:30'
tabla2.loc[tabla2.Time == '07h45', 'Time'] = '07:45'
tabla2.loc[tabla2.Time == 'Late afternoon', 'Time'] = '18:00'
tabla2.loc[tabla2.Time == '17h00', 'Time'] = '17:00'
tabla2.loc[tabla2.Time == '18h00', 'Time'] = '18:00'
tabla2.loc[tabla2.Time == '14h00', 'Time'] = '14:00'
tabla2.loc[tabla2.Time == 'Morning', 'Time'] = '10:00'
tabla2.loc[tabla2.Time == '15h00', 'Time'] = '15:00'
tabla2.loc[tabla2.Time == '22h00', 'Time'] = '22:00'
tabla2.loc[tabla2.Time == 'Night', 'Time'] = '20:00'

In [252]:
tabla2

,Date Numerica,Date,Year,Type,Country,State,Location,Activity,Name,Sex,...,Injury,Fatal (Y/N),Time,Species,Investigator or Source,Formato pdf,Localizador Uniforma de Recursos,Case Number.1,Case Number.2,original order
0,2018.06.25,25-Jun-2018,2018,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,...,"No injury to occupant, outrigger canoe and pad...",N,18:00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303
1,2018.06.18,18-Jun-2018,2018,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,...,Minor injury to left thigh,N,14h00 -15h00,,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302
2,2018.06.09,09-Jun-2018,2018,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,...,Injury to left lower leg from surfboard skeg,N,07:45,,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301
3,2018.06.08,08-Jun-2018,2018,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,No exist,M,...,Minor injury to lower leg,N,,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300
4,2018.06.04,04-Jun-2018,2018,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,...,Lacerations to leg & hand shark PROVOKED INCIDENT,N,,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25718,0,,No year info,,,,,,,,...,,,,,,,,,,
25719,0,,No year info,,,,,,,,...,,,,,,,,,,
25720,0,,No year info,,,,,,,,...,,,,,,,,,,
25721,0,,No year info,,,,,,,,...,,,,,,,,,,
25722,0,,No year info,,,,,,,,...,,,,,,,,,,